= Sway Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:mako: https://wayland.emersion.fr/mako/[mako]
:Sirula: https://github.com/DorianRudolph/sirula[Sirula]
:Sway: https://swaywm.org/[Sway]
:sway-interactive-screenshot: https://github.com/moverest/sway-interactive-screenshot[sway-interactive-screenshot]
:swaylock: https://github.com/swaywm/swaylock[swaylock]
:swayidle: https://github.com/swaywm/swayidle[swayidle]

My configuration for {Sway}.

== Usage

This repository contains my configuration file for {Sway}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Set Up

Install Sway and these settings with the following instructions.

. Install the `mako`, `sway`, `swaylock`, `swayidle`, and `waybar` packages along with `lxpolkit` for Polkit authentication.
Toolbox will be used to build Sirula below, so install that, too.
DNF:::
+
[,sh]
----
sudo dnf -y install git lxpolkit mako sway swayidle swaylock toolbox waybar
----

rpm-ostree:::
+
[,sh]
----
sudo rpm-ostree install lxpolkit mako sway swayidle swaylock waybar
----

. Install the {Sirula} application launcher to have access to Flatpak applications.

.. Clone Sirula's repository. 
+
[,sh]
----
git -C ~/Projects clone https://github.com/DorianRudolph/sirula.git
----

.. Change into the project directory.
+
[,sh]
----
cd ~/Projects/sirula
----

.. Install the required dependencies. 
This can be done in a toolbox as shown here to avoid messing with your base system.
+
[,sh]
----
toolbox run sudo dnf -y install cargo gtk3-devel gtk-layer-shell-devel
----

.. Now build and install Sirula locally with Cargo.
+
[,sh]
----
toolbox run cargo install --path .
----

.. Add `~/.cargo/bin` to your `PATH` for Cargo's sake.
+
[,sh]
----
fish_add_path -U ~/.cargo/bin
----

. Install the dependencies for {sway-interactive-screenshot}.
+
[,sh]
----
sudo rpm-ostree install fuzzel grim slurp swappy dragon wf-recorder
----

. Reboot to apply the updates.
+
[,sh]
----
sudo systemctl reboot
----

. Install the `sway-interactive-screenshot` script to `/usr/local/bin`.
+
[,sh]
----
curl -L https://raw.githubusercontent.com/moverest/sway-interactive-screenshot/master/sway-interactive-screenshot \
  | sudo tee /usr/local/bin/sway-interactive-screenshot
----

. Make the script executable.
+
[,sh]
----
sudo chmod +x /usr/local/bin/sway-interactive-screenshot
----

=== Configure

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Create the Mako configuration directory _~/.config/mako_, the Sway configuration directory _~/.config/sway_, and the swaylock configuration directory _~/.config/swaylock_.
+
[,sh]
----
mkdir -p ~/.config/mako ~/.config/sway ~/.config/swaylock
----

. Copy the provided `config` file into the Sway configuration directory.
+
[,sh]
----
for config_directory in mako sway swaylock; do cp ~/Projects/sway-config/$config_directory/config ~/.config/$config_directory/config; end
----

. Reload mako.
+
[,sh]
----
makoctl reload
----

=== Update

To update the settings in this repository from an existing installation, follow these steps.

. If you haven't already done so, clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Copy the Mako, Sway, and swaylock `config` files from the appropriate location to the Git repository.
+
[,sh]
----
for config_directory in mako sway swaylock; do cp ~/.config/$config_directory/config ~/Projects/sway-config/$config_directory/config; end
----

. Validate the Sway configuration file.
+
[,sh]
----
sway --validate ~/Projects/sway-config/config
----

. Stage the updated file.
+
[,sh]
----
git -C ~/Projects/sway-config add -A
----

. Commit.
+
[,sh]
----
git -C ~/Projects/sway-config commit -m "Update configuration putting all others to shame"
----

. Push the changes back to the central repository.
+
[,sh]
----
git -C ~/Projects/sway-config push
----

// todo Add instructions for using a merge tool to merge disparate settings files.

== Additional Steps

For a smooth integration with Sway, I've found the couple of next steps to be necessary for certain odds-and-ends to work.

. Configure gnome-keyring to be unlocked on login in your shell.
This example uses the fish shell.
+
.~/.config/fish/conf.d/gnome-keyring.fish
[,sh]
----
if test -n "$DESKTOP_SESSION" -a -z "$container"
    for env_var in (gnome-keyring-daemon --start)
        set -x (echo $env_var | string split "=")
    end
end
----

. For JetBrains IDE's to work, enable the `` environment variable.
Again, this sets the variable for the fish shell.
+
[,sh]
----
set -Ux _JAVA_AWT_WM_NONREPARENTING 1
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2020-2023 Jordan Williams

== Authors

mailto:{email}[{author}]
