= Sway Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Sway: https://swaywm.org/[Sway]
:Fedora-Sericea: https://fedoraproject.org/sericea/[Fedora Sericea]
:sway-config-fedora: https://gitlab.com/fedora/sigs/sway/sway-config-fedora[sway-config-fedora]

My {Sway} configuration on {Fedora-Sericea}.

== Usage

This repository contains my tweaks for the {sway-config-fedora} used by the F Fedora Sericea.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Symlink the `sway` directory to `~/.config/sway`.
+
[,sh]
----
ln --relative --symbolic ~/Projects/sway-config/sway ~/.config/sway
----

. Reload Sway.
+
[,sh]
----
swaymsg reload
----

== Additional Steps

For a smooth integration with Sway, I've found the couple of next steps to be necessary for certain odds-and-ends to work.

. Install the gcr package.
+
[,sh]
----
sudo rpm-ostree install gcr
----

. Reboot.
+
[,sh]
----
sudo systemctl reboot
----

. Enable the gcr SSH agent socket.
+
[,sh]
----
systemctl --user enable --now gcr-ssh-agent.socket
----

. Set `SSH_AUTH_SOCK` to the gcr socket.
+
[,sh]
----
set -Ux SSH_AUTH_SOCK $XDG_RUNTIME_DIR/gcr/ssh
----

. For JetBrains IDE's to work, enable the `_JAVA_AWT_WM_NONREPARENTING` environment variable.
Again, this sets the variable for the fish shell.
+
[,sh]
----
set -Ux _JAVA_AWT_WM_NONREPARENTING 1
----

=== SwayAudioIdleInhibit

https://github.com/ErikReider/SwayAudioIdleInhibit[SwayAudioIdleInhibit] prevents swayidle from activating when audio is being played or received via PulseAudio or Pipewire's PulseAudio implementation.

. Install the required tools.
+
[,sh]
----
sudo dnf -y install gcc-c++ git meson ninja-build pulseaudio-libs-devel wayland-devel wayland-protocols-devel
----

. Clone the `SwayAudioIdleInhibit` Git repository.
+
[,sh]
----
git clone https://github.com/ErikReider/SwayAudioIdleInhibit.git
----

. Change to the project directory.
+
[,sh]
----
cd SwayAudioIdleInhibit
----

. Configure the build.
+
[,sh]
----
meson setup build
----

. Compile.
+
[,sh]
----
meson compile -C build
----

. Install.
+
[,sh]
----
sudo meson install -C build
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2020-2023 Jordan Williams

== Authors

mailto:{email}[{author}]
