= Sway Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Sway: https://swaywm.org/[Sway]
:Fedora-Sericea: https://fedoraproject.org/sericea/[Fedora Sericea]

My {Sway} configuration on {Fedora-Sericea}.

== Usage

This repository contains my tweaks for the Fedora Sericea Sway configuration.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Configure

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Create the configuration directory _~/.config/sway/config.d_.
+
[,sh]
----
mkdir -p ~/.config/sway/config.d
----

. Copy the provided config files into the Sway configuration directory.
+
[,sh]
----
cp sway/config.d/*.conf ~/.config/sway/config.d/
----

. Reload Sway.
+
[,sh]
----
swaymsg reload
----

=== Update

To update the settings in this repository from an existing installation, follow these steps.

. If you haven't already done so, clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Copy the Mako, Sway, and swaylock `config` files from the appropriate location to the Git repository.
+
[,sh]
----
cp ~/.config/sway/config.d/*.conf ~/Projects/sway-config/sway/config.d/
----

. Stage the updated file.
+
[,sh]
----
git -C ~/Projects/sway-config add -A
----

. Commit.
+
[,sh]
----
git -C ~/Projects/sway-config commit -m "Update configuration putting all others to shame"
----

. Push the changes back to the central repository.
+
[,sh]
----
git -C ~/Projects/sway-config push
----

== Additional Steps

For a smooth integration with Sway, I've found the couple of next steps to be necessary for certain odds-and-ends to work.

. Configure gnome-keyring to be unlocked on login in your shell.
This example uses the fish shell.
+
.~/.config/fish/conf.d/gnome-keyring.fish
[,sh]
----
if test -n "$DESKTOP_SESSION" -a -z "$container"
    for env_var in (gnome-keyring-daemon --start)
        set -x (echo $env_var | string split "=")
    end
end
----

. For JetBrains IDE's to work, enable the `` environment variable.
Again, this sets the variable for the fish shell.
+
[,sh]
----
set -Ux _JAVA_AWT_WM_NONREPARENTING 1
----

=== SwayAudioIdleInhibit

https://github.com/ErikReider/SwayAudioIdleInhibit[SwayAudioIdleInhibit] prevents swayidle from activating when audio is being played or received via PulseAudio or Pipewire's PulseAudio implementation.

. Install the required tools.
+
[,sh]
----
sudo dnf -y install gcc-c++ git meson ninja-build pulseaudio-libs-devel wayland-devel wayland-protocols-devel
----

. Clone the `SwayAudioIdleInhibit` Git repository.
+
[,sh]
----
git clone https://github.com/ErikReider/SwayAudioIdleInhibit.git
----

. Change to the project directory.
+
[,sh]
----
cd SwayAudioIdleInhibit
----

. Configure the build.
+
[,sh]
----
meson setup build
----

. Compile.
+
[,sh]
----
meson compile -C build
----

. Install.
+
[,sh]
----
sudo meson install -C build
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2020-2023 Jordan Williams

== Authors

mailto:{email}[{author}]
