= Sway Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Sirula: https://github.com/DorianRudolph/sirula[Sirula]
:Sway: https://swaywm.org/[Sway]
:swaylock: https://github.com/swaywm/swaylock[swaylock]
:swayidle: https://github.com/swaywm/swayidle[swayidle]

My configuration for {Sway}.

== Usage

This repository contains my configuration file for {Sway}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Set Up

Install Sway and these settings with the following instructions.

. Install the `sway`, `swaylock`, `swayidle`, and `waybar` packages along with `lxpolkit` for Polkit authentication.
Toolbox will be used to build Sirula below, so install that, too.
DNF:::
+
[,sh]
----
sudo dnf -y install git lxpolkit sway swayidle swaylock toolbox waybar
----

rpm-ostree:::
+
[,sh]
----
sudo rpm-ostree install lxpolkit sway swayidle swaylock waybar
----

. Install the {Sirula} application launcher to have access to Flatpak applications.

.. Clone Sirula's repository. 
+
[,sh]
----
git -C ~/Projects clone https://github.com/DorianRudolph/sirula.git
----

.. Change into the project directory.
+
[,sh]
----
cd ~/Projects/sirula
----

.. Install the required dependencies. 
This can be done in a toolbox as shown here to avoid messing with your base system.
+
[,sh]
----
toolbox run sudo dnf -y install cargo gtk3-devel gtk-layer-shell-devel
----

.. Now build and install Sirula locally with Cargo.
+
[,sh]
----
toolbox run cargo install --path .
----

.. Add `~/.cargo/bin` to your `PATH` for Cargo's sake.
+
[,sh]
----
fish_add_path -U ~/.cargo/bin
----

=== Configure

. Configure gnome-keyring to be unlocked on login in your shell.
This example uses the fish shell.
+
.~/.config/fish/conf.d/gnome-keyring.fish
[,sh]
----
if test -n "$DESKTOP_SESSION"
    for env_var in (gnome-keyring-daemon --start)
        set -x (echo $env_var | string split "=")
    end
end
----

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Create the Sway configuration directory, _~/.config/sway/_.
+
[,sh]
----
mkdir -p ~/.config/sway/
----

. Copy the provided `config` file into the Sway configuration directory.
+
[,sh]
----
cp ~/Projects/sway-config/config ~/.config/sway/
----

=== Update

To update the settings in this repository from an existing installation, follow these steps.

. If you haven't already done so, clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Copy the `config` and `ignore` files from the appropriate location to the Git repository.
+
[,sh]
----
cp ~/.config/sway/config ~/Projects/sway-config/
----

. Validate the Sway configuration file.
+
[,sh]
----
sway --validate ~/Projects/sway-config/config
----

. Stage the updated file.
+
[,sh]
----
git -C ~/Projects/sway-config add -A
----

. Commit.
+
[,sh]
----
git -C ~/Projects/sway-config commit -m "Update configuration putting all others to shame"
----

. Push the changes back to the central repository.
+
[,sh]
----
git -C ~/Projects/sway-config push
----

// todo Add instructions for using a merge tool to merge disparate settings files.

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2020-2022 Jordan Williams

== Authors

mailto:{email}[{author}]
