= Sway Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Sirula: https://github.com/DorianRudolph/sirula[Sirula]
:Sway: https://swaywm.org/[Sway]

My configuration for {Sway}.

== Usage

This repository contains my configuration file for {Sway}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Set Up

Install Sway and these settings with the following instructions.

. Install the `sway` and `waybar` packages along with `lxpolkit` for Polkit authentication.
Toolbox will be used to build Sirula below, so install that, too.
DNF:::
+
[source,sh]
----
sudo dnf -y install git lxpolkit sway toolbox waybar
----

rpm-ostree:::
+
[source,sh]
----
sudo rpm-ostree install git lxpolkit sway toolbox waybar
----

. Install the {Sirula} application launcher to have access to Flatpak applications.

.. Clone Sirula's repository. 
+
[source,sh]
----
git -C ~/Projects clone https://github.com/DorianRudolph/sirula.git
----

.. Change into the project directory.
+
[source,sh]
----
cd ~/Projects/sirula
----

.. Install the required dependencies. 
This can be done in a toolbox as shown here to avoid messing with your base system.
+
[source,sh]
----
toolbox run sudo dnf -y install cargo gtk3-devel gtk-layer-shell-devel
----

.. Now build and install Sirula locally with Cargo.
+
[source,sh]
----
toolbox run cargo install --path .
----

=== Configure

. Clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Create the Sway configuration directory, _~/.config/sway/_.
+
[source,sh]
----
mkdir -p ~/.config/sway/
----

. Copy the provided `config` file into the Sway configuration directory.
+
[source,sh]
----
cp ~/Projects/sway-config/config ~/.config/sway/
----

=== Update

To update the settings in this repository from an existing installation, follow these steps.

. If you haven't already done so, clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/sway-config.git
----

. Copy the `config` and `ignore` files from the appropriate location to the Git repository.
+
[source,sh]
----
cp ~/.config/sway/config ~/Projects/sway-config/
----

. Validate the Sway configuration file.
+
[source,sh]
----
sway --validate ~/Projects/sway-config/config
----

. Stage the updated file.
+
[source,sh]
----
git -C ~/Projects/sway-config add -A
----

. Commit.
+
[source,sh]
----
git -C ~/Projects/sway-config commit -m "Update configuration putting all others to shame"
----

. Push the changes back to the central repository.
+
[source,sh]
----
git -C ~/Projects/sway-config push
----

// todo Add instructions for using a merge tool to merge disparate settings files.

== Troubleshooting

=== Proprietary NVidia Drivers + GDM

It's now possible to use the proprietary NVidia drivers with Sway, but it requires modifying the command-line for sway to include the flag `--my-next-gpu-wont-be-nvidia`.
To configure GDM to include this flag, create a new desktop entry.

. Create the necessary configuration directory in `/usr/local` to avoid problems editing the default file under `/usr`. 
+
[source,sh]
----
sudo mkdir -p /usr/local/share/wayland-sessions
----

. Copy the default `sway.desktop` file to `/usr/local/share/wayland-sessions/sway.desktop`.
+
[source,sh]
----
sudo cp /usr/share/wayland-sessions/sway.desktop /usr/local/share/wayland-sessions/sway.desktop
----

. Now add the `--my-next-gpu-wont-be-nvidia` flag after the `sway` command in the desktop file.
+
[source,sh]
----
sudo sed -i 's/Exec=sway/Exec=sway --my-next-gpu-wont-be-nvidia/' /usr/local/share/wayland-sessions/sway.desktop
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2020-2021 Jordan Williams

== Authors

mailto:{email}[{author}]
